spring:
  application:
    name: expenses-tracker-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/expenses_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
